import './globals.css'
import Script from 'next/script'
import ToastProvider from '@/components/ToastProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          {children}
        </ToastProvider>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/vanta@0.5.24/dist/vanta.net.min.js" strategy="beforeInteractive" />
        <Script id="vanta-script" strategy="afterInteractive">
          {`
            VANTA.NET({
              el: "#vanta-bg",
              mouseControls: true,
              touchControls: true,
              gyroControls: false,
              minHeight: 200.00,
              minWidth: 200.00,
              scale: 1.00,
              scaleMobile: 1.00,
              color: 0xb11b1b,
              backgroundColor: 0x0,
              points: 9.00
            })
          `}
        </Script>
      </body>
    </html>
  )
}
